# Generated by Django 5.2.5 on 2026-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_stockproductofraccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_MANUAL', 'Manual entry'), ('SALIDA_MANUAL', 'Manual exit'), ('AJUSTE_POSITIVO', 'Positive adjustment'), ('AJUSTE_NEGATIVO', 'Negative adjustment'), ('CONSOLIDACION_FRACCIONADA', 'Fractional stock consolidation'), ('DESCONSOLIDACION_FRACCIONADA', 'Fractional stock deconsolidation'), ('RESERVA_PEDIDO', 'Order reservation'), ('LIBERACION_PEDIDO', 'Order reservation release'), ('SALIDA_PICKING', 'Picking deduction'), ('AJUSTE_PICKING', 'Picking adjustment'), ('ENTRADA_NOTA_CREDITO', 'Credit note return'), ('REVERSO_NOTA_CREDITO', 'Credit note reversal'), ('ANULACION_PEDIDO', 'Order cancellation reversal')], max_length=30),
        ),
    ]
