# Generated by Django 5.2.5 on 2026-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_force_signed_stock_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpresentacion',
            name='stock_disponible',
            field=models.IntegerField(default=0, help_text='Legacy cached available. Prefer dual-ledger Available from inventario.availability.'),
        ),
        migrations.AlterField(
            model_name='stockpresentacion',
            name='stock_fisico',
            field=models.IntegerField(default=0, help_text='Quick Inventory from QuickBooks (packages). May be negative when QuickBooks reports oversold quantity.'),
        ),
        migrations.AlterField(
            model_name='stockpresentacion',
            name='stock_reservado',
            field=models.PositiveIntegerField(default=0, help_text='Legacy reserved packages counter (not used for Available).'),
        ),
    ]
