# Generated by Django 5.2.5 on 2026-07-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_invoiceitem_es_regalo'),
        ('inventario', '0015_alter_stockpresentacion_dual_ledger_help_text'),
        ('pedidos', '0017_pedidoitem_es_regalo'),
        ('productos', '0029_configuraciondescuentosporcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomovimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], db_index=True, default='', help_text='Used by Emergency Inventory Adjustment. Blank for non-temporary movements.', max_length=20),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='observacion_resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_resueltos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventariomovimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_MANUAL', 'Manual entry'), ('SALIDA_MANUAL', 'Manual exit'), ('AJUSTE_POSITIVO', 'Positive adjustment'), ('AJUSTE_NEGATIVO', 'Negative adjustment'), ('AJUSTE_EMERGENCIA', 'Emergency Inventory Adjustment'), ('CONSOLIDACION_FRACCIONADA', 'Fractional stock consolidation'), ('DESCONSOLIDACION_FRACCIONADA', 'Fractional stock deconsolidation'), ('RESERVA_PEDIDO', 'Order reservation'), ('LIBERACION_PEDIDO', 'Order reservation release'), ('SALIDA_PICKING', 'Picking deduction'), ('SALIDA_REGALO', 'Free promotional product deduction'), ('AJUSTE_PICKING', 'Picking adjustment'), ('ENTRADA_NOTA_CREDITO', 'Credit note return'), ('REVERSO_NOTA_CREDITO', 'Credit note reversal'), ('ANULACION_PEDIDO', 'Order cancellation reversal')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='inventariomovimiento',
            index=models.Index(fields=['presentacion', 'tipo', 'estado'], name='inv_mov_pres_tipo_estado_idx'),
        ),
    ]
