# Generated by Django 6.0.2 on 2026-03-05 18:18

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = wrap_add_field_operations('clientes', [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='USA', max_length=100),
        ),
    
    ])

