# Generated by Django 5.2.5 on 2026-07-10 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_normalize_customer_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='QuickBooks A/R balance: positive = customer owes La Tortilla (due balance / debit); negative = credit in favor of the customer (credit note balance).', max_digits=12),
        ),
    ]
