# Generated by Django 5.2.5 on 2026-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_invoice_notaajuste_quickbooks_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MIXTO', 'Cash + cheque'), ('MULTIPLE', 'Multiple methods'), ('TRANSFERENCIA', 'Transfer'), ('TARJETA', 'Card'), ('ZELLE', 'Zelle'), ('ACH', 'ACH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notaajuste',
            name='motivo',
            field=models.CharField(choices=[('DAMAGE', 'Physical damage / transport'), ('DEFECT', 'Factory defect / quality issue'), ('MISSING_ITEM', 'Missing item'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
