# Generated by Django 5.2.5 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_alter_delivery_metodo_pago_alter_notaajuste_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaajuste',
            name='motivo',
            field=models.CharField(
                choices=[
                    ('DAMAGE', 'Damage / transport'),
                    ('DEFECT', 'Factory defect / quality issue'),
                    ('MISSING_ITEM', 'Missing item'),
                    ('OTHER', 'Other'),
                ],
                max_length=20,
            ),
        ),
    ]
