# Generated by Django 5.2.5 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_quickbooksconnection_sync_state_and_conflict_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbooksimportconflict',
            name='entity_type',
            field=models.CharField(
                choices=[
                    ('CUSTOMER', 'Customer'),
                    ('ITEM', 'Item'),
                    ('INVOICE', 'Invoice'),
                    ('CREDIT_MEMO', 'Credit memo'),
                    ('BILL', 'Bill'),
                ],
                max_length=30,
            ),
        ),
    ]
