# Generated by Django 5.2.5 on 2026-06-29 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, db_index=True, max_length=30)),
                ('action_category', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTION', 'Action'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SYNC', 'Sync')], db_index=True, max_length=20)),
                ('action_label', models.CharField(max_length=255)),
                ('http_method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['-created_at', 'actor'], name='auditoria_a_created_997d48_idx'), models.Index(fields=['action_category', '-created_at'], name='auditoria_a_action__09a0b2_idx')],
            },
        ),
    ]
