# Generated by Django 5.2.5 on 2026-07-30 16:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0016_cliente_web_access_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='Paco', max_length=80)),
                ('welcome_message', models.TextField(default='Hola.\n\nSoy Paco, el asistente virtual de La Tortilla Grocery.\n\n¿Quieres que te ayude a registrarte?')),
                ('personality', models.TextField(default='Amable, claro, proactivo y orientado a ayudar a completar una compra.')),
                ('sales_goal', models.TextField(default='Guiar al cliente hacia el siguiente paso útil: registro, catálogo, carrito, solicitud o confirmación.')),
                ('system_prompt', models.TextField(blank=True)),
                ('default_language', models.CharField(default='es', max_length=8)),
                ('chat_model', models.CharField(default='gpt-4.1-mini', max_length=100)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default='0.30', max_digits=3)),
                ('max_messages_per_hour', models.PositiveIntegerField(default=30)),
                ('max_message_chars', models.PositiveIntegerField(default=2000)),
                ('handoff_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('enable_home', models.BooleanField(default=True)),
                ('enable_catalog', models.BooleanField(default=True)),
                ('enable_customer_portal', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Assistant configuration',
                'verbose_name_plural': 'AI Assistant configuration',
            },
        ),
        migrations.CreateModel(
            name='AssistantKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(default='es', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_url', models.CharField(blank=True, max_length=300)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_id', models.UUIDField(db_index=True)),
                ('language', models.CharField(default='es', max_length=8)),
                ('first_page', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to='clientes.cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantDomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACCOUNT_APPROVED', 'Account approved'), ('QUOTE_READY', 'Quote ready'), ('ORDER_DISPATCHED', 'Order dispatched'), ('ORDER_DELIVERED', 'Order delivered')], max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_events', to='clientes.cliente')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=12)),
                ('content', models.TextField()),
                ('redacted_content', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_payload', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.assistantconversation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(unique=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('last_notified_events', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_state', to='clientes.cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantGuidedTourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField()),
                ('tour_key', models.CharField(max_length=80)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('visitor_id', 'tour_key')},
            },
        ),
        migrations.CreateModel(
            name='AssistantKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_assistant.assistantknowledgedocument')),
            ],
            options={
                'ordering': ('document_id', 'position'),
                'unique_together': {('document', 'position')},
            },
        ),
    ]
