# Generated by Django 5.2.5 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_assistantvisitorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantdomainevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('ACCOUNT_APPROVED', 'Account approved'),
                    ('ACCOUNT_NEEDS_CORRECTION', 'Account needs correction'),
                    ('QUOTE_READY', 'Quote ready'),
                    ('ORDER_DISPATCHED', 'Order dispatched'),
                    ('ORDER_DELIVERED', 'Order delivered'),
                ],
                max_length=40,
            ),
        ),
    ]
