# Generated by Django 5.2.5 on 2026-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacion_backoffice_pricing_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Draft'), ('ENVIADA', 'Sent by client'), ('LISTA_PARA_CONFIRMACION', 'Ready for confirmation'), ('CONFIRMADA_CLIENTE', 'Confirmed by client'), ('CANCELADA_CLIENTE', 'Canceled by client'), ('APROBADA', 'Approved'), ('RECHAZADA', 'Rejected')], default='BORRADOR', max_length=30),
        ),
    ]
