# Generated by Django 5.2.5 on 2026-07-10 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0012_take_order_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(blank=True, default=dict)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_order_drafts', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_order_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-actualizada_en',),
                'constraints': [models.UniqueConstraint(fields=('vendedor', 'cliente'), name='vendedores_takeorderdraft_vendedor_cliente_uniq')],
            },
        ),
    ]
