# Generated by Django 6.0.2 on 2026-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
