from django.urls import path

from .views import (
    create_database_backup_stored,
    create_system_backup_stored,
    database_backups_center,
    quickbooks_callback,
    quickbooks_center,
    quickbooks_database_backup,
    quickbooks_database_backup_download,
    backup_restore_status,
    restore_backup_from_center,
    restore_backup_upload,
    system_backup,
    system_backup_download,
    update_backup_schedule_preference,
    quickbooks_import_customers,
    quickbooks_import_customers_to_local,
    quickbooks_import_credit_memos,
    quickbooks_import_conflicts,
    quickbooks_import_conflict_dismiss,
    quickbooks_import_conflicts_bulk_dismiss,
    quickbooks_import_conflict_link,
    quickbooks_import_conflict_retry,
    quickbooks_import_accounting_documents_to_local,
    quickbooks_import_invoices,
    quickbooks_import_items,
    quickbooks_import_items_to_local,
    quickbooks_refresh_linked_items_to_local,
    quickbooks_pull_items_sync_to_local,
    quickbooks_login,
    quickbooks_pull_sync_to_local,
    quickbooks_status,
    quickbooks_sync_adjustment_notes_batch,
    quickbooks_sync_adjustment_note,
    quickbooks_sync_customers_batch,
    quickbooks_sync_customer,
    quickbooks_sync_invoices_batch,
    quickbooks_sync_invoice,
    quickbooks_sync_products_batch,
    quickbooks_sync_product,
    quickbooks_test_connection,
    quickbooks_start_task,
    quickbooks_task_status,
)


urlpatterns = [
    path('', quickbooks_center, name='quickbooks_center'),
    path('database-backups', database_backups_center, name='database_backups_center'),
    path('login', quickbooks_login, name='quickbooks_login'),
    path('callback/', quickbooks_callback, name='quickbooks_callback'),
    path('status', quickbooks_status, name='quickbooks_status'),
    path('test-connection', quickbooks_test_connection, name='quickbooks_test_connection'),
    path('import/customers', quickbooks_import_customers, name='quickbooks_import_customers'),
    path('import/customers/to-local', quickbooks_import_customers_to_local, name='quickbooks_import_customers_to_local'),
    path('import/items', quickbooks_import_items, name='quickbooks_import_items'),
    path('import/items/to-local', quickbooks_import_items_to_local, name='quickbooks_import_items_to_local'),
    path('refresh/items/linked', quickbooks_refresh_linked_items_to_local, name='quickbooks_refresh_linked_items_to_local'),
    path('pull-sync/items/to-local', quickbooks_pull_items_sync_to_local, name='quickbooks_pull_items_sync_to_local'),
    path('import/invoices', quickbooks_import_invoices, name='quickbooks_import_invoices'),
    path('import/credit-memos', quickbooks_import_credit_memos, name='quickbooks_import_credit_memos'),
    path('import/accounting-documents/to-local', quickbooks_import_accounting_documents_to_local, name='quickbooks_import_accounting_documents_to_local'),
    path('task/start', quickbooks_start_task, name='quickbooks_start_task'),
    path('task/status/<str:task_id>', quickbooks_task_status, name='quickbooks_task_status'),
    path('import/conflicts', quickbooks_import_conflicts, name='quickbooks_import_conflicts'),
    path('import/conflicts/<int:conflict_id>/retry', quickbooks_import_conflict_retry, name='quickbooks_import_conflict_retry'),
    path('import/conflicts/<int:conflict_id>/link', quickbooks_import_conflict_link, name='quickbooks_import_conflict_link'),
    path('import/conflicts/<int:conflict_id>/dismiss', quickbooks_import_conflict_dismiss, name='quickbooks_import_conflict_dismiss'),
    path('import/conflicts/bulk-dismiss', quickbooks_import_conflicts_bulk_dismiss, name='quickbooks_import_conflicts_bulk_dismiss'),
    path('backup/preferences', update_backup_schedule_preference, name='update_backup_schedule_preference'),
    path('backup/restore', restore_backup_from_center, name='restore_backup_from_center'),
    path('backup/restore/upload', restore_backup_upload, name='restore_backup_upload'),
    path('backup/restore/status/<str:job_id>', backup_restore_status, name='backup_restore_status'),
    path('backup/database/create', create_database_backup_stored, name='create_database_backup_stored'),
    path('backup/system/create', create_system_backup_stored, name='create_system_backup_stored'),
    path('backup/system', system_backup, name='system_backup'),
    path('backup/system/<str:backup_name>', system_backup_download, name='system_backup_download'),
    path('backup/database', quickbooks_database_backup, name='quickbooks_database_backup'),
    path('backup/database/<str:backup_name>', quickbooks_database_backup_download, name='quickbooks_database_backup_download'),
    path('pull-sync/to-local', quickbooks_pull_sync_to_local, name='quickbooks_pull_sync_to_local'),
    path('sync/customer/<int:cliente_id>', quickbooks_sync_customer, name='quickbooks_sync_customer'),
    path('sync/product/<int:presentacion_id>', quickbooks_sync_product, name='quickbooks_sync_product'),
    path('sync/invoice/<int:invoice_id>', quickbooks_sync_invoice, name='quickbooks_sync_invoice'),
    path('sync/adjustment-note/<int:note_id>', quickbooks_sync_adjustment_note, name='quickbooks_sync_adjustment_note'),
    path('sync/customers/batch', quickbooks_sync_customers_batch, name='quickbooks_sync_customers_batch'),
    path('sync/products/batch', quickbooks_sync_products_batch, name='quickbooks_sync_products_batch'),
    path('sync/invoices/batch', quickbooks_sync_invoices_batch, name='quickbooks_sync_invoices_batch'),
    path('sync/adjustment-notes/batch', quickbooks_sync_adjustment_notes_batch, name='quickbooks_sync_adjustment_notes_batch'),
]
