# Generated by Django 6.0.2 on 2026-03-03 01:21

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='presentacion',
            name='tipo_contenido',
            field=models.CharField(default='unidades', max_length=50),
        ),
    
    ])

