# Generated by Django 6.0.2 on 2026-03-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='tipo_contenido',
            field=models.CharField(default='unidades', max_length=50),
        ),
    ]
