# Generated by Django 6.0.2 on 2026-03-04 03:08

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_marca_producto_marca'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='marca',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='productos.categoria'),
        ),
    
    ])

