# Generated by Django 6.0.2 on 2026-03-05 21:21

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_marca_categorias'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.RenameField(
            model_name='presentacion',
            old_name='precio',
            new_name='precio_1',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='precio_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='precio_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='precio_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion',
            name='precio_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    
    ])

