# Generated by Django 6.0.2 on 2026-03-07 00:07

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_precio_presentacion_precio_1_and_more'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    
    ])

