# Generated by Django 6.0.2 on 2026-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_marca_logo_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
