# Generated by Django 6.0.2 on 2026-03-12 00:34

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_marca_logo_producto_destacado'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    
    ])

