# Generated by Django 6.0.2 on 2026-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marca',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
