# Generated by Django 6.0.2 on 2026-03-12 17:57

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_categoria_nombre_en_marca_nombre_en_and_more'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='presentacion',
            name='tipo_contenido_en',
            field=models.CharField(blank=True, max_length=50),
        ),
    
    ])

