# Generated by Django 6.0.2 on 2026-03-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_categoria_nombre_en_marca_nombre_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='tipo_contenido_en',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
