# Generated by Django 6.0.2 on 2026-03-14 23:10

from django.db import migrations, models
from config.core.migration_utils import wrap_add_field_operations



class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_presentacion_tipo_contenido_en'),
    ]

    operations = wrap_add_field_operations('productos', [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras único del producto', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    
    ])

