# Generated by Django 5.2.5 on 2026-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_producto_presentacion_quickbooks_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='quickbooks_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
