# Generated by Django 5.2.5 on 2026-07-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_presentacion_pallet_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Name')),
                ('descripcion', models.CharField(blank=True, help_text='Short text shown in the catalog, e.g. "Buy 10 cases and get 15% off".', max_length=255, verbose_name='Customer description')),
                ('cantidad_minima', models.PositiveIntegerField(default=1, verbose_name='Minimum quantity')),
                ('tipo_beneficio', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed dollars')], default='PERCENT', max_length=10, verbose_name='Benefit type')),
                ('valor_beneficio', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 15) or dollars per unit (e.g. 2.00), depending on type.', max_digits=10, verbose_name='Benefit value')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('activa', models.BooleanField(default=True, verbose_name='Active')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('presentacion', models.ForeignKey(blank=True, help_text='Leave empty to apply to any presentation of the product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.presentacion', verbose_name='Presentation')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='productos.producto', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-activa', '-creada_en'],
            },
        ),
    ]
