# Generated by Django 5.2.5 on 2026-04-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_make_usuario_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('COTIZACION', 'Cotizacion'), ('PEDIDO', 'Pedido'), ('NOTA_AJUSTE', 'Nota de ajuste')], max_length=20),
        ),
    ]
