# Generated by Django 6.0.2 on 2026-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('negocio', models.CharField(blank=True, max_length=150, null=True)),
                ('comentario', models.TextField()),
                ('estrellas', models.IntegerField(default=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', '-creado'],
            },
        ),
    ]
