# Generated by Django 5.2.5 on 2026-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homecontenido_cards_and_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_direccion_linea_1',
            field=models.CharField(default='1666 Roswell Rd Bldg 100', max_length=180),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_direccion_linea_2',
            field=models.CharField(default='Marietta, GA 30062-3639', max_length=180),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_email',
            field=models.EmailField(default='latortilla@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_telefono',
            field=models.CharField(default='+1 (470) 967 2782', max_length=60),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_titulo',
            field=models.CharField(default='Contactanos', max_length=120),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_contacto_titulo_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_empresa_descripcion',
            field=models.TextField(default='La Tortilla Grocery LLC es un distribuidor mayorista de productos latinos de confianza. Abastecemos tiendas, supermercados y restaurantes con calidad, precios competitivos y entregas eficientes.'),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_empresa_descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_empresa_titulo',
            field=models.CharField(default='La Tortilla Grocery', max_length=120),
        ),
        migrations.AddField(
            model_name='homecontenido',
            name='footer_empresa_titulo_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
