from django.core.management.base import BaseCommand, CommandError

from config.integrations.backups import restore_database_backup_file


class Command(BaseCommand):
    help = 'Restore the database from a backup file generated by backup_database.'

    def add_arguments(self, parser):
        parser.add_argument('--file', required=True, help='Backup file name from media/backups/database/ or an explicit file path.')
        parser.add_argument('--flush', action='store_true', help='Delete existing database records before restoring the backup.')
        parser.add_argument('--confirm', default='', help='Type RESTORE to confirm this operation.')

    def handle(self, *args, **options):
        if str(options.get('confirm') or '').strip().upper() != 'RESTORE':
            raise CommandError('Restore cancelled. Re-run with --confirm=RESTORE.')

        try:
            backup_name = restore_database_backup_file(
                source=options.get('file'),
                flush=bool(options.get('flush')),
            )
        except Exception as exc:
            raise CommandError(str(exc)) from exc

        self.stdout.write(self.style.SUCCESS(f'Database restored from: {backup_name}'))